application: toxa-tracer
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets/css
  static_dir: assets/css
- url: /assets/fonts
  static_dir: assets/fonts
- url: /assets/img
  static_dir: assets/img
- url: /assets/js
  static_dir: assets/js
- url: .*
  script: main.APP

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
- name: markupsafe
  version: latest